project:
  type: website

website:
  favicon: logo.png
  title: "Tec & Soc."
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/pedroorden/
      - icon: github
        href: https://github.com/pedroorden
      - icon: book
        href: https://independent.academia.edu/PedroOrden

format:
  html:
    theme:
     light: pulse
     dark: cyborg
    css: styles.css



